name = "ulid-generator"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2022-05-16"

[build]
command = "npm install"

[durable_objects]
bindings = [{name = "MONOTONIC_ULID", class_name = "MonotonicULID"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MonotonicULID"]
